### PR TITLE
add support to cli for cabal dns entries

### PR DESCRIPTION
**Pull request by cblgh**
This PR uses a fork of [dat-dns](https://github.com/datprotocol/dat-dns). It supports everything dat-dns supports, but with the cabal:// prefix instead. 

Additionally, the cli config is used for persistent caching of resolved DNS entries.

The easiest way to pin a cabal key on a hostname is by creating a file called `cabal` in the webroot of your domain, inside a `.well-known` folder. See the record at https://cblgh.org/.well-known/cabal

We also don't invalidate resolved entries even if the TTL has expired, but a warning is added. If the ttl has expired however, and the domain is reachable and the `cabal` file present in `.well-known`, the new key will be resolved and cached locally.

Try it out against cabal://cblgh.org: `node cli.js cabal://cblgh.org`

### CODE REVIEW

**Comment by nikolaiwarner** [comment]
Rad!

If the contents of .well-known/cabal change, do clients see that change the next time they connect?

**Comment by todrobbins** [comment]
PS: @cblgh we should bring https://github.com/cblgh/cabal-dns into the cabal org. ✌🏻

**Comment by cblgh** [comment]
@todrobbins yeah i would, but i'm going to try to bring the functionality into dat-dns via a PR so that we don't need to maintain a separate fork :)

**Comment by todrobbins** [comment]
ah, that makes sense since they're cousins and all.

**Comment by cblgh** [comment]
@nikolaiwarner yes they do!

**Comment by cblgh** [comment]
ps if nobody else has comments, i'm going to go ahead and merge this later tonight

**Comment by cblgh** [comment]
🎉 🎉 🎉

**Pull request merged**
