### PR TITLE
Add --temp flag

### PR DESCRIPTION
**Pull request by cblgh**
Introduces a `--temp` flag as per https://github.com/cabal-club/cabal/issues/99.

This creates a  [`random-access-memory`](https://www.npmjs.com/package/random-access-memory) database and uses that instead of any locally saved databases. 
I think it should work with all the other connection options without a hitch.

Usage:
`cabal cabal://123...fad --temp`
`cabal pub --temp`

### CODE REVIEW

**Comment by ralphtheninja** [comment]
This is pretty cool actually since it allows you to create on the fly / ephemeral chats!

**Comment by nikolaiwarner** [comment]
love it! +1

**Comment by ralphtheninja** [comment]
Imma meeerging :wink:

**Comment by cblgh** [comment]
yay~!

**Pull request merged**
